# Generated by Django 4.2.3 on 2023-07-04 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("image_generation", "0002_imagegeneration"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ImageGeneration",
        ),
    ]
