# Generated by Django 4.2.2 on 2023-07-04 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("image_generation", "0004_generatedimage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GeneratedImage",
        ),
    ]
