# Generated by Django 4.2.3 on 2023-07-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_generation", "0005_delete_generatedimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_field", models.TextField()),
                ("datetime_field", models.DateTimeField(auto_now_add=True)),
                ("image_field", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
